const DATA = [
  {
    short_name: "EA",
    name: "Elite Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Angular",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MA",
    name: "Monster Admin",
    email: "Single Use",
    phone: "Venessa Fern",
    role: "Vue Js",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MP",
    name: "Material Pro Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Bootstrap",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "AA",
    name: "Ample Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "React",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "EA",
    name: "Elite Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Angular",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MA",
    name: "Monster Admin",
    email: "Single Use",
    phone: "Venessa Fern",
    role: "Vue Js",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MP",
    name: "Material Pro Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Bootstrap",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "AA",
    name: "Ample Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "React",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "EA",
    name: "Elite Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Angular",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MA",
    name: "Monster Admin",
    email: "Single Use",
    phone: "Venessa Fern",
    role: "Vue Js",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MP",
    name: "Material Pro Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Bootstrap",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "AA",
    name: "Ample Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "React",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "EA",
    name: "Elite Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Angular",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MA",
    name: "Monster Admin",
    email: "Single Use",
    phone: "Venessa Fern",
    role: "Vue Js",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MP",
    name: "Material Pro Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Bootstrap",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "AA",
    name: "Ample Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "React",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "EA",
    name: "Elite Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Angular",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MA",
    name: "Monster Admin",
    email: "Single Use",
    phone: "Venessa Fern",
    role: "Vue Js",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MP",
    name: "Material Pro Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Bootstrap",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "AA",
    name: "Ample Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "React",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "EA",
    name: "Elite Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Angular",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MA",
    name: "Monster Admin",
    email: "Single Use",
    phone: "Venessa Fern",
    role: "Vue Js",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MP",
    name: "Material Pro Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Bootstrap",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "AA",
    name: "Ample Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "React",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "EA",
    name: "Elite Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Angular",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MA",
    name: "Monster Admin",
    email: "Single Use",
    phone: "Venessa Fern",
    role: "Vue Js",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MP",
    name: "Material Pro Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Bootstrap",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "AA",
    name: "Ample Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "React",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "EA",
    name: "Elite Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Angular",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MA",
    name: "Monster Admin",
    email: "Single Use",
    phone: "Venessa Fern",
    role: "Vue Js",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MP",
    name: "Material Pro Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Bootstrap",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "AA",
    name: "Ample Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "React",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "EA",
    name: "Elite Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Angular",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MA",
    name: "Monster Admin",
    email: "Single Use",
    phone: "Venessa Fern",
    role: "Vue Js",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MP",
    name: "Material Pro Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Bootstrap",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "AA",
    name: "Ample Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "React",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "EA",
    name: "Elite Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Angular",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MA",
    name: "Monster Admin",
    email: "Single Use",
    phone: "Venessa Fern",
    role: "Vue Js",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MP",
    name: "Material Pro Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Bootstrap",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "AA",
    name: "Ample Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "React",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "EA",
    name: "Elite Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Angular",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MA",
    name: "Monster Admin",
    email: "Single Use",
    phone: "Venessa Fern",
    role: "Vue Js",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MP",
    name: "Material Pro Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Bootstrap",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "AA",
    name: "Ample Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "React",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "EA",
    name: "Elite Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Angular",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MA",
    name: "Monster Admin",
    email: "Single Use",
    phone: "Venessa Fern",
    role: "Vue Js",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MP",
    name: "Material Pro Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Bootstrap",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "AA",
    name: "Ample Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "React",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "EA",
    name: "Elite Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Angular",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MA",
    name: "Monster Admin",
    email: "Single Use",
    phone: "Venessa Fern",
    role: "Vue Js",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MP",
    name: "Material Pro Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Bootstrap",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "AA",
    name: "Ample Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "React",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "EA",
    name: "Elite Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Angular",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MA",
    name: "Monster Admin",
    email: "Single Use",
    phone: "Venessa Fern",
    role: "Vue Js",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MP",
    name: "Material Pro Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Bootstrap",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "AA",
    name: "Ample Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "React",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "EA",
    name: "Elite Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Angular",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MA",
    name: "Monster Admin",
    email: "Single Use",
    phone: "Venessa Fern",
    role: "Vue Js",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "MP",
    name: "Material Pro Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "Bootstrap",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
  {
    short_name: "AA",
    name: "Ample Admin",
    email: "Single Use",
    phone: "John Doe",
    role: "React",
    tickets: 46,
    change_profile: 365,
    remove_admin: 2850.06,
  },
];

export default DATA;
